# Generated by Django 2.0.2 on 2019-06-10 16:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('time_period', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('post_url', models.URLField(blank=True, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('category_set', models.ManyToManyField(blank=True, related_name='post', to='jobMatchingApi.JobCategory')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='accounts.Recruiter')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MatchedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('post_url', models.URLField(blank=True, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_posts', to='accounts.JobSeeker')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(blank=True, default='Ingénieur Informatique', max_length=200, null=True)),
                ('experience_level', models.CharField(blank=True, default='Débutant 1 ans', max_length=50, null=True)),
                ('carrier_objective', models.TextField(blank=True, default='Nothing For the moment', null=True)),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('seeker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='accounts.JobSeeker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('time_period', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='jobMatchingApi.Resume')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_background', to='jobMatchingApi.Resume'),
        ),
    ]
