# Generated by Django 2.0.2 on 2019-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobMatchingApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category_set',
            field=models.ManyToManyField(blank=True, to='jobMatchingApi.JobCategory'),
        ),
    ]
