# Generated by Django 2.0.2 on 2019-06-11 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190610_2243'),
        ('jobMatchingApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedposts',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_matched_posts', to='accounts.Recruiter'),
        ),
    ]
