# Generated by Django 2.0.2 on 2019-06-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190610_2243'),
        ('jobMatchingApi', '0002_matchedposts_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedResumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(blank=True, max_length=255)),
                ('seeker_name', models.CharField(blank=True, max_length=255)),
                ('cosine_distance', models.FloatField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_resumes', to='accounts.Recruiter')),
            ],
        ),
    ]
